# Generated by Django 5.0.1 on 2025-02-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_image', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('quoted', 'Quoted'), ('negotiating', 'Negotiating'), ('ordered', 'Ordered'), ('invoiced', 'Invoiced'), ('delivered', 'Delivered'), ('closed', 'Closed'), ('lost', 'Lost')], default='new', max_length=20)),
            ],
        ),
    ]
