# Generated by Django 5.0.1 on 2025-02-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company_image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
