# Generated by Django 5.0.1 on 2025-02-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_lead_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('€', 'Euro')], default='$', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(choices=[('retail', 'Retail Industry'), ('banking', 'Banking'), ('hotels', 'Hotels'), ('financial_services', 'Financial Services'), ('insurance', 'Insurance')], default='retail', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('person', 'Person'), ('organization', 'Organization')], default='person', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_type',
            field=models.CharField(choices=[('work', 'Work'), ('home', 'Home')], default='work', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('phone_calls', 'Phone Calls'), ('social_media', 'Social Media'), ('referral_sites', 'Referral Sites'), ('web_analytics', 'Web Analytics'), ('previous_purchase', 'Previous Purchase')], default='phone_calls', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('select_people', 'Select People')], default='public', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
