# Generated by Django 5.1.6 on 2025-03-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_lead_currency_lead_description_lead_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='company_address',
        ),
    ]
