# Generated by Django 5.1.6 on 2025-03-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_lead_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='qualification_step',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('interested', 'Interested'), ('needs_analysis', 'Needs Analysis'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('converted', 'Converted to Customer'), ('disqualified', 'Disqualified')], default='contacted', max_length=50),
        ),
    ]
