# Generated by Django 5.1.6 on 2025-03-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_lead_company_address_lead_qualification_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='qualification_step',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='visibility',
        ),
    ]
